---

##
## @param composer_auth_github_token
##
- name: "composer:set:auth:github:get-current | Check current access token"
  command: "{{ composer_executable_path }} config -q -g github-oauth.github.com"
  register: "composer_config_github_token"
  changed_when: false
  ignore_errors: yes

- name: "composer:set:auth:github | Set access token for composer"
  command: "{{ composer_executable_path }} config -g github-oauth.github.com {{ composer_auth_github_token }}"
  when: "{{ (composer_auth_github_token is defined) and (composer_auth_github_token|trim != composer_config_github_token.stdout|trim) }}"
